service: auth-server

provider:
 name: aws
 runtime: nodejs18.x
 region: eu-central-1
 timeout: 30 # optional, in seconds, default is 6
 environment:
   CLIENT_ID: ${file(config.json):CLIENT_ID}
   CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
   CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
 getAuthURL:
   handler: handler.getAuthURL
   events:
     - http:
         path: api/get-auth-url
         method: get
         cors: true
 getAccessToken:
   handler: handler.getAccessToken
   events:
     - http:
          path: api/get-access-token/{code}     
          method: get  
          cors: true
 getCalendarEvents:
    handler: handler.getCalenderEvents
    events:
      - http:
          path: api/get-calendar-events/{access_token}
          method: get
          cors: true
